apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-sk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp-sk
  template:
    metadata:
      labels:
        app: nodeapp-sk
    spec:
      nodeSelector:
        "kubernetes.io/os": linux  #this is important if you are building it from MAC /Windows to Linux
      containers:
      - name: nodeserver
        image: arctictern/aksdemodocker:latest  #Docker hub location, where I have published the image
        ports:
        - containerPort: 3000
